sudo: required
language: node_js
node_js:
  - "node"
before_script: chmod 0777 ./deploy.sh
jobs:
  include:
    - stage: deploy_frontend
      if: branch = master OR branch = staging OR branch = development
      script: ./deploy.sh
deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    region: $AWS_DEFAULT_REGION
    bucket: $S3_PROD_BUCKET_NAME
    local_dir: ./source/dist
    skip_cleanup: true
    acl: public_read
    cache_control: "max-age=21600"
    on:
      branch: master
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_STAGING_BUCKET_NAME
    region: $AWS_DEFAULT_REGION
    skip_cleanup: true
    acl: public_read
    local_dir: ./source/dist
    cache_control: "max-age=21600"
    on:
      branch: staging
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY_ID
    secret_access_key: $AWS_SECRET_ACCESS_KEY
    bucket: $S3_DEVELOPMENT_BUCKET_NAME
    region: $AWS_DEFAULT_REGION
    skip_cleanup: true
    acl: public_read
    local_dir: ./source/dist
    cache_control: "max-age=21600"
    on:
      branch: development
